---
title: Introduction to Election Analytics (Week 1)
author: Lucy Ding
date: '2022-09-14'
slug: []
categories: []
tags: []
---

```{r setup, include=FALSE}
# Hiding all code output
knitr::opts_chunk$set(echo = FALSE)

# Loading libraries
library(tidyverse)
library(sf)
library(plotly)
library(usmap)
library(rmapshaper)

# Reading in data
house_vote_seat_party <- read_csv("house nationwide vote and seat share by party 1948-2020.csv")
house_vote_district <- read_csv("house party vote share by district 1948-2020.csv")

# Load geographic data for 114th congress - 2014 election
get_congress_map <- function(cong=114) {
  tmp_file <- tempfile()
  tmp_dir <- tempdir()
  zp <- sprintf("https://cdmaps.polisci.ucla.edu/shp/districts114.zip",cong)
  download.file(zp, tmp_file)
  unzip(zipfile = tmp_file, exdir = tmp_dir)
  fpath <- paste(tmp_dir, sprintf("districtShapes/districts114.shp",cong), sep = "/")
  st_read(fpath)
}

# Load 114th congress
cd114 <- get_congress_map(114)
```

```{r}
# Find vote-share margins for the 2018 election and plot for all states
margin_2014_state <- house_vote_district %>%
  filter(raceYear == 2014) %>%
  select(raceYear, State, district_num, district_id, RepVotes, DemVotes) %>%
  group_by(State) %>%
  summarize(voteshare_margin = (sum(RepVotes)-sum(DemVotes))/(sum(RepVotes)+sum(DemVotes))) %>%
  rename(state = State)

plot_usmap(data = margin_2014_state, regions = "states", values = "voteshare_margin", labels = TRUE) +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", 
                      name = "Two-Party \nVoteshare Margin") +
  theme_void() +
  labs(title = "Two-Party Vote-Share Margin by State",
       subtitle = "2014 Midterm Election")
```

```{r}
# Find vote-share margins for the 2014 election
margin_2014 <- house_vote_district %>%
  filter(raceYear == 2014) %>%
  mutate(voteshare_margin = (RepVotes - DemVotes)/(RepVotes + DemVotes)) %>%
  select(raceYear, State, district_num, district_id, voteshare_margin) %>%
  mutate(DISTRICT = as.character(district_num)) %>%
  rename(STATENAME = State)
  
margin_2014_geom <- left_join(margin_2014, cd114, by = c("STATENAME", "DISTRICT")) %>%
  filter(!STATENAME %in% c("Alaska","Hawaii")) %>%
  st_as_sf() %>%
  ms_simplify()

ggplot() +
  geom_sf(data = margin_2014_geom, mapping = aes(fill = voteshare_margin)) +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", 
                         name = "Two-Party \nVoteshare Margin") +
  theme_void() +
  labs(title = "Two-Party Vote-Share Margin by District",
       subtitle = "2014 Midterm Election")
```

