---
title: Post-Election Campaign Narrative
author: R package build
date: '2022-12-09'
slug: []
categories: []
tags: []
---

*Disclaimer: For this cycle, I did work on Angie Craig's campaign, so I may have a slightly biased view of what occurred. The statements that I make should not be taken as statements from the campaign. This largely comes from my own opinions and research of the events and news coverage, as well as knowledge from the class Gov 1347.*

# Introduction

Throughout the 2022 midterm elections, I closely followed the race in Minnesota's 2nd Congressional District between Angie Craig (D) and Tyler Kistner (R). Angie Craig first ran for this position in 2016 against the Republican incumbent and lost, but ran again in 2018 and won and has held the seat ever since. Kistner lost the race in 2020 with 45.9% of the vote to Craig's 48.2% and in 2022, lost the race again with 45.8% to Craig's 50.9%. 

This district is comprised of a more urban/suburban area to the north, which typically leans blue, and a more rural area to the south. The district was redistricted in 2020 to comprise of roughly the same urban/suburban are in the north, but some different rural areas to the south. The overall partisan lean of the district, however, did not change much. Something unique to this district is it's high voter turnout, usually around 60-70%, and its third party - the Legal Marijuana Now Party. This third party in particular tends to take votes from the Democratic candidate, and information spread this campaign cycle that not only were the Republicans likely were [supporting](https://minnesotareformer.com/2022/09/09/minn-pot-party-candidate-for-u-s-house-seat-has-gop-ties-dems-allege-shes-a-spoiler/) the third party campaign with money, they were also providing them assistance on how to run their campaign. About a month before the election, however, Paula Overby, the candidate for the Legal Marijuana Now Party, passed away. They still did get 3.3% of the vote. This is a similar story to what happened in 2020, where Adam Weeks, the candidate for the Legal Marijuana Now Party, passed away before the election but still received 5.8% of the vote.

The district tended to be categorized as between a Toss-Up and Lean Democratic district. Limited [polling](https://www.realclearpolitics.com/epolls/2022/house/mn/minnesota_2nd_district_kistner_vs_craig-7465.html) had Craig up by only one point, Craig was the incumbent by about a two point margin in the election previous, and redistricting was not predicted to have changed much for the district. My final prediction for the district, using an ensemble of a pooled model of fundamentals and the partisan lean of a district after redistricting, predicted that the Democratic candidate would win with 50.97% of the two-party vote-share. This was actually very close to the actual vote-share, which was 50.9%, and also to the actual two-party vote-share of 52.64%. This indicates that Angie Craig did either the same/marginally better than most had predicted her to do.

# Craig's Campaign

This election was a rematch of 2020 between Tyler Kistner and Angie Craig. This cycle, [Craig](https://angiecraig.com/issues/) largely ran her campaign on the economy, reproductive rights, public safety, and healthcare, while [Kistner](https://www.tylerkistnerforcongress.com/issues) ran on the economy (inflation, jobs, opportunity), and public safety. For Kistner, this was definitely the correct issues to run on. Lynn Vavreck tells us in her 2009 book, "The message matters: the economy and presidential campaigns." that a challenging candidate in a bad economy should tailor their message to be about the economy, pointing out the flaws of the incumbent and arguing that they would do a better job (Vavreck, 2009). Here, the Democrats are the incumbent party, and inflation was topping the news stories at the time. This means that Kistner did well to hammer in the message that Democrats were harming the economy, and that he would reverse it. This also means that Craig also would have done well to focus on the economy less, which she did do to an extent through bringing in the issues of reproductive rights for women and public safety. Unlike some other Democrats, Craig [supports](https://angiecraig.com/wp-content/uploads/2022/10/Rep.-Angie-Craigs-Record-on-Law-Enforcement-3.pdf) and enjoys a lot of support from law enforcement, in contrast to Kistner.

On advertising, at the last [report](https://www.opensecrets.org/races/summary?cycle=2022&id=MN02) on October 19th, Craig had raised \$7 million, which is more than double what Kistner raised, but this was dwarfed by the \$9.6 million and $9.1 million, respectively, of outside spending for each side. This [makes](https://www.mprnews.org/episode/2022/11/02/takeaways-from-minnesotas-spendiest-congressional-race) this race the 24th most expensive race in the country. Most of the outside spending was on attack ads against each candidate. While Craig [focused](https://www.mprnews.org/episode/2022/11/02/takeaways-from-minnesotas-spendiest-congressional-race) on advertising online with digital advertising firms, Kistner spent more on direct mail and fliers. Before seeing the final amount each campaign respectively spent on ads, a safe conclusion could be that Craig and Kistner both spent somewhat heavily, with Craig spending slightly more. Ads have been shown to be somewhat effective at persuasion, but less effective at turnout and education (Huber and Arceneaux, 2007). For this election, it may be possible to assume that the effects of the large volume of ads somewhat canceled out, however, Craig may have gotten a slight edge, which would tie in with her doing slightly better than most predictions.

There were also a couple of controversies in this campaign, largely surrounding Kistner. Already mentioned above was the support that Republicans provided to the third party - Legal Marijuana Now. In addition, Kistner tend to have some messaging issues surrounding abortion - though he had numerous past statements showing that he was pro-life, he seemed to appear to try to [mask](https://apnews.com/article/abortion-2022-midterm-elections-us-supreme-court-health-arizona-ab2ae055e64b22472108909869f2a405) this position, perhaps sensing its unfavorability. Kistner also made [claims](https://www.bloomberg.com/graphics/us-election-risk-index/all-election-denier-officials/?leadSource=uverify%20wall) about election fraud in 2020 and refused to say that Joe Biden "won" the 2020 presidential election, [using](https://www.dropbox.com/s/u424mrs1pi6lc2b/Kistner%3A%20Biden%20%22is%22%20the%20President.mov?dl=0) the language of election deniers. Another controversy came after he shied away at [releasing](https://www.swnewsmedia.com/prior_lake_american/news/election/gop-veteran-candidates-clash-over-records-before-2nd-district-party-convention/article_2b4d3027-09fc-553d-b730-7ea8b8ee0466.html) his military service record. After a lot of pushing, he did release it, where it became clear that he was never a combat veteran, as had been claimed. Like many other Republican candidates this year, Kistner seemed to be somewhat of a bad candidate - possessing a record that dragged him down amidst a year where Republicans should have performed better than 2020. Indeed, Kistner did see a small drop in support in 2022, and Craig saw a moderate jump in support.

# Conclusion

Overall, this district did perform as it was thought to have. It was a relatively close race that invited a good amount of outside spending. This district should remain between lean Democratic and a toss-up in future elections. Craig, as evidenced through her better fundraising numbers, endorsements, and relative lack of relative controversy, ran a better campaign than Kistner, who was in general a lower quality candidate. Against a different Republican candidate, however, that didn't have the same controversies, and that could secure greater fundraising for advertisements, successfully support a third party candidate to take votes from Craig, and secure key endorsements, Craig's path to victory may not have been as clear.









