---
title: "R Notebook"
output: html_notebook
---

# Libraries

```{r}
# Load libraries
library(tidyverse)
library(janitor)
library(glmnet)
library(sf)
library(plotly)
library(usmap)
library(rmapshaper)
library(blogdown)
library(gridExtra)
library(stargazer)
library(lubridate)
library(caret)
library(leaps)
library(ggthemes)
library(usdata)
library(gt)
library(gtsummary)
```

# Data

```{r, message = FALSE}
turnout <- read_csv("turnout_2012_2020.csv")
turnout22 <- read_csv("turnout_2022.csv")
electionresults <- read_csv("incumb_dist_1948-2022.csv")
genericballot <- read_csv("polls_df.csv")
gdp_q <- read_csv("GDP_quarterly.csv")
```

```{r}
genericballot <- genericballot %>% 
  mutate(poll_data = as.Date(genericballot$poll_date, format = "%m/%d/%Y")) %>%
  filter(days_until_election <= 52) %>% 
         # the closest poll to election day for 1952 was 51.5
  group_by(year, party) %>% 
  summarise(average_support = mean(support)) %>%
  filter(party =="D")

# Filter out data for Q6
gdp_q6 <- gdp_q %>%
  filter(quarter_cycle == 6) %>% 
  rename(gdp_q6 = GDPC1)

# Filter out data for Q7
gdp_q7 <- gdp_q %>%
  filter(quarter_cycle == 7) %>% 
  rename(gdp_q7 = GDPC1)

# creating gdp_q_final
gdp_q_final <- left_join(gdp_q7, gdp_q6, by = "year") %>% 
  mutate(gdp_q7_q6 = (gdp_q7 - gdp_q6) / gdp_q6 * 100) %>% # percent difference
  rename(gdp_percent_difference = gdp_q7_q6) %>% 
  select(year, gdp_percent_difference)

incumbency <- electionresults %>%  
  mutate(incumb = ifelse(winner_candidate == "DemCandidate",1,0)) %>% 
  mutate(year = year + 2) %>% 
  select (year, st_cd_fips, incumb)


# adding generic ballot average to turnout
df <- left_join(electionresults, genericballot, by = "year") %>%
  left_join(gdp_q_final, by = "year") %>%
  left_join(incumbency, by = c("year", "st_cd_fips")) %>% 
  select(year, state, district_num, winner_party, RepVotes, DemVotes,
         DemVotesMajorPercent, st_cd_fips,
         average_support, gdp_percent_difference, incumb) %>%
  drop_na(incumb)

state_dists <- unique(turnout$st_cd_fips)
```

```{r}
turnout14 <- turnout %>%
  filter(year == 2014) %>%
  select(year, turnout, st_cd_fips) %>%
  distinct() %>%
  distinct(st_cd_fips, .keep_all = TRUE)
turnout18 <- turnout %>%
  filter(year == 2018) %>%
  select(year, turnout, st_cd_fips) %>%
  distinct() %>%
  distinct(st_cd_fips, .keep_all = TRUE)
turnout22_fixed <- left_join(turnout14, turnout18, by = "st_cd_fips") %>%
  mutate(hist_avg = (turnout.x + turnout.y)/2) %>%
  select(st_cd_fips, hist_avg)
turnout22 <- left_join(turnout22, turnout22_fixed, by = "st_cd_fips") %>%
  select(-historical_turnout_by_district)
```

```{r}
#write.csv(df, "district_model_data.csv")
```



# Model with Turnout

```{r, warning = FALSE}
# Instantiate lists
models <- list()
r2 <- c()
preds <- c()
preds_high <- c()
preds_low <- c()
coeff_support <- c()
coeff_turnout <- c()
coeff_gdp <- c()
coeff_incumb <- c()

# Loop through each district, model and predict
for (sd in state_dists){
  # Filter for dataframe with just district sd
  temp <- turnout %>%
    filter(st_cd_fips == sd)
  
  # Fit linear model for dem two-party vote-share
  m <- lm(DemVotesMajorPercent ~ average_support + turnout + gdp_percent_difference + incumb, data = temp)
  
  # Add model to list of models
  models[[length(models)+1]] <- m
  
  # Find r^2, coeffs, and add to list
  r2 <- c(r2, summary(m)$adj.r.squared)
  coeff_support <- c(coeff_support, summary(m)$coefficients[2])
  coeff_turnout <- c(coeff_turnout, summary(m)$coefficients[3])
  coeff_gdp <- c(coeff_gdp, summary(m)$coefficients[4])
  coeff_incumb <- c(coeff_incumb, summary(m)$coefficients[5])
  
  # Make a 2022 prediction and append to list
  new_data <- turnout22 %>%
    filter(st_cd_fips == sd) %>%
    rename(turnout = hist_avg)
  preds <- c(preds, predict(m, new_data))
  preds_high <- c(preds_high, predict(m, new_data %>% mutate(turnout = turnout + 8)))
  preds_low <- c(preds_low, predict(m, new_data %>% mutate(turnout = turnout - 8)))
}

output <- tibble(state_dists, preds, preds_high, preds_low, r2, coeff_gdp, coeff_incumb, coeff_support, coeff_turnout)
```

```{r}
state_dists[435]
```


```{r}
stargazer(m, type = "text")
```


```{r}
tbl_regression(m)
```



```{r}
preds_df <- tibble(state_dists, preds, preds_high, preds_low)
#write.csv(preds_df, "preds_df.csv")
```


```{r}
length(preds[preds <= 50])
length(preds[preds > 50])
```

```{r}
length(preds[preds_high <= 50])
length(preds[preds_high > 50])
```

```{r}
length(preds[preds_low <= 50])
length(preds[preds_low > 50])
```

```{r}
ggplot(turnout %>% filter(year == 2018), aes(x = DemVotesMajorPercent)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "Actual 2018 House Election Results",
       subtitle = "House Districts",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  ylim(0,50)
```

```{r}
ggplot(output %>% mutate(preds = ifelse(preds > 100, 100, preds),
                                        preds = ifelse(preds < 0, 0, preds)), 
       aes(x = preds)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "2022 Election Predictions - Turnout Model",
       subtitle = "Average Turnout",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  xlim(-5, 105) +
  ylim(0,50)

ggplot(output %>% mutate(preds_high = ifelse(preds_high > 100, 100, preds_high),
                                        preds_high = ifelse(preds_high < 0, 0, preds_high)), 
       aes(x = preds_high)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "2022 Election Predictions - Turnout Model",
       subtitle = "High Turnout",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  xlim(-5, 105) +
  ylim(0,50)

ggplot(output %>% mutate(preds_low = ifelse(preds_low > 100, 100, preds_low),
                                        preds_low = ifelse(preds_low < 0, 0, preds_low)), 
       aes(x = preds_low)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "2022 Election Predictions - Turnout Model",
       subtitle = "Low Turnout",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  xlim(-5, 105) +
  ylim(0,50)
```

```{r}
output_stacked <- output %>% 
  pivot_longer(cols = c(preds, preds_high, preds_low), names_to = "preds") %>%
  mutate(value = ifelse(value > 100, 100, value), 
         value = ifelse(value < 0, 0, value))

ggplot(output_stacked, aes(x=value, fill=preds)) +
  geom_histogram(alpha=0.2, position='identity')
```



```{r}
ggplot(output, aes(x = r2)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "R-Squared Values for Turnout Models in Each District",
       subtitle = "House Districts",
       x = "R-Squared",
       y = "Count")
```

```{r}
p1 <- ggplot(output, aes(x = coeff_gdp)) +
  geom_histogram(bins = 30) + 
  theme_few() +
  labs(x = "GDP Coefficient",
       y = "Count")
p2 <- ggplot(output, aes(x = coeff_support)) +
  geom_histogram(bins = 30) +
  theme_few() +
  labs(x = "Generic Ballot Coefficient",
       y = "Count")
p3 <- ggplot(output, aes(x = coeff_turnout)) +
  geom_histogram(bins = 30) + 
  theme_few() +
  labs(x = "Turnout Coefficient",
       y = "Count")
grid.arrange(p1, p2, p3)
```

```{r}
p1 <- ggplot(output, aes(x = coeff_gdp)) +
  geom_histogram(bins = 30, color = "white") + xlim(-2.5, 2.5) + 
  geom_vline(xintercept = median(output$coeff_gdp, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "GDP Coefficient",
       y = "Count") +
  ylim(0, 130)

p2 <- ggplot(output, aes(x = coeff_support)) +
  geom_histogram(bins = 30, color = "white") + xlim(-10, 10) +  
  geom_vline(xintercept = median(output$coeff_support, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Generic Ballot Coefficient",
       y = "Count") +
  ylim(0, 130)

p3 <- ggplot(output, aes(x = coeff_turnout)) +
  geom_histogram(bins = 30, color = "white") + xlim(-2.5, 2.5) + 
  geom_vline(xintercept = median(output$coeff_turnout, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Turnout Coefficient",
       y = "Count") +
  ylim(0, 130)

p4 <- ggplot(output, aes(x = coeff_incumb)) +
  geom_histogram(bins = 30, color = "white") + xlim(-20, 20) + 
  geom_vline(xintercept = median(output$coeff_incumb, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Incumbency Coefficient",
       y = "Count") +
  ylim(0, 130)

grid.arrange(p1, p2,p3)
```

```{r}
p3
```


# Models v2

```{r, warning = FALSE}
models <- list()
r2 <- c()
preds <- c()
coeff_support <- c()
coeff_gdp <- c()
coeff_incumb <- c()
for (sd in state_dists){
  # Filter for dataframe with just district sd
  temp <- df %>%
    filter(year != 2022) %>%
    filter(st_cd_fips == sd)
  
  # Fit linear model for dem two-party vote-share
  m <- lm(DemVotesMajorPercent ~ average_support + gdp_percent_difference + incumb, data = temp)
  
  # Add model to list of models
  models[[length(models)+1]] <- m
  
  # Find r^2, coeffs, and add to list
  r2 <- c(r2, summary(m)$adj.r.squared)
  coeff_support <- c(coeff_support, summary(m)$coefficients[2])
  coeff_gdp <- c(coeff_gdp, summary(m)$coefficients[3])
  coeff_incumb <- c(coeff_incumb, summary(m)$coefficients[4])
  
  # Make a 2022 prediction and append to list
  new_data <- turnout22 %>%
    filter(st_cd_fips == sd) %>%
    rename(turnout = hist_avg)
  preds <- c(preds, predict(m, new_data))
}
```

```{r}
stargazer(m, type = "text")
```


```{r}
better_preds <- tibble(state_dists, preds)
output_v2 <- tibble(r2, preds, coeff_support, coeff_gdp, coeff_incumb)
#write.csv(better_preds, "better_preds.csv")
```

```{r}
ggplot(output_v2, aes(x = r2)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "R-Squared Values for Models w/o Turnout in Each District",
       subtitle = "House Districts",
       x = "R-Squared",
       y = "Count")
```

```{r}
ggplot(output_v2 %>% mutate(preds = ifelse(preds > 100, 100, preds),
                                        preds = ifelse(preds < 0, 0, preds)), 
       aes(x = preds)) +
  geom_histogram(bins = 30, color = "white") +
  theme_few() +
  labs(title = "2022 Election Predictions - Model w/o Turnout",
       subtitle = "House Districts",
       x = "Democratic Two-Party Vote-Share (%)",
       y = "Count") +
  xlim(-5, 105) +
  ylim(0,50)
```

```{r}
p1 <- ggplot(output_v2, aes(x = coeff_gdp)) +
  geom_histogram(bins = 30, color = "white") + xlim(-2.5, 2.5) + 
  geom_vline(xintercept = median(output_v2$coeff_gdp, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "GDP Coefficient",
       y = "Count") +
  ylim(0, 150)

p2 <- ggplot(output_v2, aes(x = coeff_support)) +
  geom_histogram(bins = 30, color = "white") + xlim(-10, 10) +  
  geom_vline(xintercept = median(output_v2$coeff_support, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Generic Ballot Coefficient",
       y = "Count") +
  ylim(0, 150)

p3 <- ggplot(output_v2, aes(x = coeff_incumb)) +
  geom_histogram(bins = 30, color = "white") + xlim(-60, 60) + 
  geom_vline(xintercept = median(output_v2$coeff_incumb, na.rm = TRUE),
             color = "red", size = 1) + 
  theme_few() +
  labs(x = "Incumbency Coefficient",
       y = "Count") +
  ylim(0, 150)

grid.arrange(p1, p2, p3)
```

```{r}
p3
```


```{r}
summary(m)
```

```{r}
length(preds[preds <= 50])
length(preds[preds > 50])
```




